---
title: "202303_InflationConcern"
author: "Wai"
date: "2023-03-15"
output: html_document
---

# Packages
```{r}
library(dplyr)
library(ggplot2)
library(devtools)
library(patchwork)
library(sysfonts)
library(showtext)
```

# Dataset
```{r}
inflat <- read.csv("202303_UKInflationConcern.csv")

View(inflat)
head(inflat)
```

# data cleaning
```{r}
as.Date(paste0(c("2022-01"), "-01"), format = "%Y-%m-%d")
as.Date(paste0('01-', c('07-2002')), format="%d-%m-%Y")

inflat_cleaned <- inflat %>% 
  mutate (Date = as.Date(paste0(c(Month), "-01"), format = "%Y-%m-%d"), 
          WorryNum = as.numeric(sub("%", "", Worry.Percentage))/100
          ) %>% 
  rename("cpi_agr" = "CPI..Annual.Growth.Rate.", 
         "cpi_2015" = "CPI..2015.Index.") %>% 
  mutate(cpi_agr = cpi_agr/100) %>% 
  select(Date, WorryNum, cpi_agr, cpi_2015)

View(inflat_cleaned)

```



# GGplot test
```{r}
# Text and theme
font_add_google("Roboto Slab", "Font")
main_font <- "Font"
showtext_auto(TRUE)

main_title <- "UK Inflation & Inflation Concern"
title_1 <- "Percenage of population with inflation concern"
title_2 <- "Inflation (Annual Growth Rate)"
cap_txt <- "@brit.viz | Data: OECD.org & ipsos.com"
y_axis_1 <- "testing"
y_axis_2 <- "testing222"
text_1 <- "March 2022 \ndata not \navaliable"


bg <- "#121212"
txt_c <- "#F2F2F2"
fill_c <- "#FB4F58"
# fill_c <- "#EC8C6F"
line_c <- "#FB2451"

WorryNum <-
inflat_cleaned %>% 
  ggplot(aes(y = WorryNum, x = Date)) + 
  geom_area(fill = fill_c) + 
  geom_line(color = line_c, 
            size = 1) + 
  ylim(-0.01, 0.6) + 
  scale_y_continuous(labels = scales::percent) + 
  # basic aes
  theme(
    plot.background = element_rect(fill = bg, 
                                   color = bg), 
    panel.background = element_blank(), 
    panel.grid = element_blank(), 
    
    # text
    text = element_text(color = txt_c, 
                        family = main_font, 
                        size = 10), 
    plot.title = element_text(size = 20, 
                              face = "bold"), 
    plot.title.position = "plot", 
    axis.title = element_blank(), 
    # axis.title.y = element_text(size = 10),
    axis.text = element_text(color = txt_c, 
                             family = main_font, 
                             size = 10), 
    plot.caption = element_text(size = 15, 
                                margin = margin(t = 10, b = 5)), 

    # others
    axis.ticks = element_line(color = txt_c)
    
  ) + 
  annotate("rect", 
           xmin = as.Date("2022-02-02"), 
           xmax = as.Date("2022-03-31"), 
           ymin = -0.01,
           ymax = 0.6,
           fill = bg) + 
  annotate("text", 
           x = as.Date("2022-03-01"), 
           y = 0.2, 
           label = text_1, 
           family = main_font, 
           face = "bold", 
           color = txt_c, 
           ) + 
  # annotation
  labs(title = title_1, 
       y = y_axis_1, 
       caption = cap_txt
       )

inflat_agr <-
inflat_cleaned %>%
  ggplot(aes(y = cpi_agr, x = Date)) +
    geom_area(fill = fill_c) + 
  geom_line(color = line_c, 
            size = 1) + 
  scale_y_continuous(labels = scales::percent) + 
  
  # basic aes
  theme(
    plot.background = element_rect(fill = bg, 
                                   color = bg), 
    panel.background = element_blank(), 
    panel.grid = element_blank(), 
    
    # text
    text = element_text(color = txt_c, 
                        family = main_font, 
                        size = 10), 
    plot.title = element_text(size = 20, 
                              face = "bold"), 
    plot.title.position = "plot", 
    axis.title = element_blank(), 
    # axis.title.y = element_text(size = 10), 
    axis.text = element_text(color = txt_c, 
                             family = main_font, 
                             size = 10), 
    # others
    axis.ticks = element_line(color = txt_c)) + 
    
  # annotation
  labs(title = title_2, 
       y = y_axis_2
       )


```
# Patchwork
```{r}
patchwork <-
  inflat_agr / WorryNum
patchwork + plot_annotation(
  title = main_title, 
  
  theme = theme(plot.background = element_rect(color = bg, fill = bg), 
                plot.title = element_text(margin = margin(t = 10, b = 5)))
)  & 
  theme(
    text = element_text(family = main_font, 
                        color = txt_c,
                        face = "bold", 
                        size = 25 
                        ), 
    
  )
```
# Saving test
```{r}
showtext_opts(dpi = 320)
ggsave("202303_UKInflation.png", 
       height = 8, 
       width = 8, 
       dpi = 320)
```

